[workspace]
name = "eomt"
version = "0.0.1"
description = "Your ViT is Secretly an Image Segmentation Model"
channels = ["https://prefix.dev/conda-forge"]
platforms = ["linux-64"]
requires-pixi = ">=0.62"

[system-requirements]
linux = "5.4.0"
cuda="12"



[dependencies]
gitignore-parser="==0.1.12"
matplotlib="==3.10.1"
timm="==1.0.15"
wandb="==0.19.10"
lightning="==2.5.1.post0"
transformers="==4.56.1"
scipy="==1.15.2"
pytorch="==2.7.0"
torchvision= {version = "==0.22.0", build="cuda*"}
ipykernel="==6.29.5"
fvcore="==0.1.5.post20221221"
torchmetrics="==1.7.1"
pycocotools="==2.0.8"

[pypi-dependencies]
jsonargparse = {version = "==4.38.*", extras = ["signatures"]}
